# Generated by Django 4.1.5 on 2023-02-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.CharField(max_length=200, verbose_name='썸네일'),
        ),
    ]
