# Generated by Django 4.1.5 on 2023-02-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_gallery_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='', verbose_name='사진 url'),
        ),
    ]
