# Generated by Django 4.1.5 on 2023-02-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_alter_image_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
    ]
