# Generated by Django 4.1.5 on 2023-02-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_rename_image_url_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery_id',
            field=models.ForeignKey(db_column='gallery_id', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='galleries.gallery', verbose_name='갤러리id값'),
        ),
    ]
