# Generated by Django 4.1.5 on 2023-02-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_alter_image_gallery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='썸네일'),
        ),
    ]
