# Generated by Django 4.1.5 on 2023-02-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_rename_image_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': '추억사진', 'verbose_name_plural': '추억사진들'},
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery_id',
            field=models.ForeignKey(db_column='gallery_id', on_delete=django.db.models.deletion.CASCADE, related_name='Galleryimage', to='galleries.gallery', verbose_name='갤러리id값'),
        ),
    ]
