# Generated by Django 4.1.5 on 2023-02-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0009_remove_gallery_month_remove_gallery_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
