# Generated by Django 4.1.5 on 2023-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0010_alter_gallery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
