# Generated by Django 4.1.5 on 2023-03-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0011_rename_gallery_id_gallery_id_alter_gallery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='id',
            new_name='gallery_id',
        ),
    ]
