# Generated by Django 4.1.5 on 2023-03-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0012_rename_id_gallery_gallery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.URLField(verbose_name='썸네일'),
        ),
    ]
