# Generated by Django 4.1.5 on 2023-03-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0013_alter_gallery_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='썸네일'),
        ),
    ]
