# Generated by Django 4.1.5 on 2023-02-17 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('dev_stack', models.CharField(max_length=200, verbose_name='트랙')),
                ('thumbnail', models.ImageField(max_length=200, upload_to='', verbose_name='썸네일')),
                ('description', models.TextField(blank=True, null=True, verbose_name='글 내용')),
                ('version', models.IntegerField(verbose_name='기수')),
                ('team_name', models.CharField(max_length=30, verbose_name='팀 이름')),
                ('team_member', models.JSONField(default='{}')),
                ('start_date', models.DateField(auto_now=True, verbose_name='프로젝트 시작일자')),
                ('end_date', models.DateField(auto_now=True, verbose_name='프로젝트 종료 일자')),
                ('link', models.JSONField(default='{}')),
                ('category', models.CharField(max_length=100)),
                ('member_id', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자 id값')),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='', verbose_name='사진 url')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='projects.project', verbose_name='프로젝트id값')),
            ],
            options={
                'verbose_name': '프로젝트사진',
                'verbose_name_plural': '프로젝트사진들',
            },
        ),
    ]
