# Generated by Django 4.1.5 on 2023-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_member',
            field=models.JSONField(default=dict),
        ),
    ]
