# Generated by Django 4.1.5 on 2023-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dev_stack',
            field=models.CharField(max_length=200, verbose_name='기술 스택'),
        ),
    ]
