# Generated by Django 4.1.5 on 2023-03-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_dev_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(max_length=200, verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.CharField(max_length=100, verbose_name='사진 url'),
        ),
    ]
