# Generated by Django 4.1.5 on 2023-03-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_thumbnail_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='썸네일'),
        ),
    ]
