# Generated by Django 4.1.5 on 2023-03-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(max_length=200, verbose_name='썸네일'),
        ),
    ]
