# Generated by Django 4.1.5 on 2023-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_thumbnail_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='', verbose_name='사진 url'),
        ),
    ]
