# Generated by Django 4.1.5 on 2023-03-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattendance',
            name='time',
        ),
    ]
