# Generated by Django 4.1.5 on 2023-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
