# Generated by Django 4.1.5 on 2023-02-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_management_team_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='authentication_number',
            new_name='code',
        ),
    ]
