# Generated by Django 4.1.5 on 2023-02-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_authentication_number_user_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='track',
        ),
    ]
