# Generated by Django 4.1.5 on 2023-02-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_alter_session_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='reference',
            field=models.URLField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='session',
            name='track',
            field=models.CharField(choices=[('front', 'front'), ('back', 'back'), ('desing', 'design'), ('pm', 'pm')], max_length=10, verbose_name='트랙'),
        ),
    ]
