# Generated by Django 4.1.5 on 2023-03-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_alter_session_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='presenter',
            new_name='assigner',
        ),
    ]
