# Generated by Django 4.1.5 on 2023-03-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_rename_session_id_sessionimage_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionimage',
            name='image',
            field=models.CharField(max_length=100, verbose_name='사진 url'),
        ),
    ]
