# Generated by Django 4.1.5 on 2023-03-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_rename_presenter_session_assigner'),
        ('lectures', '0008_alter_sessionimage_image'),
    ]

    operations = [
    ]
