# Generated by Django 4.1.5 on 2023-03-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_merge_20230305_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='assigner',
            new_name='presenter',
        ),
    ]
