# Generated by Django 4.1.5 on 2023-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_merge_20230305_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='assigner',
        ),
        migrations.AddField(
            model_name='session',
            name='presenter',
            field=models.CharField(default='변주현', max_length=10, verbose_name='발표자'),
        ),
        migrations.AlterField(
            model_name='session',
            name='thumbnail',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='session',
            name='track',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='트랙'),
        ),
        migrations.AlterField(
            model_name='sessionimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='사진 url'),
        ),
    ]
