# Generated by Django 4.1.5 on 2023-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0011_alter_session_presenter_alter_session_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionimage',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='', verbose_name='사진 url'),
        ),
    ]
