# Generated by Django 4.1.5 on 2023-03-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0012_alter_sessionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='track',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='트랙'),
        ),
    ]
